version: '3'
services:
  web:
    build: ./gateway
    ports:
      - ${WEB_PORT:-9000}:80
    links:
      - frontend
      - backend
  frontend:
    build: ./front-end
  backend:
    build: ./back-end
    links:
      - mysql
      - redis
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  redis:
    image: redis