version: '3'
services:
  web:
    image: mcskin/mcskin-gateway:test
    ports:
      - ${WEB_PORT:-9000}:80
    links:
      - frontend
      - backend
  frontend:
    image: mcskin/mcskin-frontend:test
  backend:
    image: mcskin/mcskin-backend:test
    links:
      - mysql
      - redis
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  redis:
    image: redis