name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Frontend image
      run: docker build ./front-end --tag mcskin/mcskin-frontend:$(date +%s)
    - uses: actions/checkout@v3
    - name: Build the Backend image
      run: docker build ./back-end --tag mcskin/mcskin-backend:$(date +%s)
    - uses: actions/checkout@v3
    - name: Build the Gateway image
      run: docker build ./gateway --tag mcskin/mcskin-gateway:$(date +%s)
