name: publish

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
      - 'develop'
jobs:
  publish-backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with: 
          images: mcskin/redstone-skin
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{branch == 'develop'}}
            type=raw,value=stable,enable={{branch == 'main'}}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
